services:
  dev:
    build:
      context: .
      args:
        INSTALL_BNL_FROM_GIT: "false"
    ports:
      - "7860:7860"
    volumes:
      - .:/code
      - ../bnl:/bnl
    command: bash -c "pip install -e /bnl && python app.py"

  prod:
    build: .
    ports:
      - "7860:7860"